#!/bin/bash

# This bash script was written by thevicraft.

if [ -z $1 ]
then
	echo "Please append an argument:"
	echo "------> install"
	echo "------> delete"
	return
fi

filename="jpg-launcher.desktop"
game_folder=$HOME/java-pixel-game
icon_location=$game_folder/launcher
icon_filename="icon-launcher-desktop.png"
icon_url="https://raw.githubusercontent.com/thevicraft/jpg-launcher/main/icon-launcher-desktop.png"
jar_filename="launcher.jar"
launcher_last_url="https://github.com/thevicraft/jpg-launcher/releases/latest/download/launcher.jar"

# delete process
if [ $1 = "delete" ]
then
	echo "Deleting the current Launcher installation..."
	# delete the .desktop file
	echo
	echo "Removing desktop entry."
	if test -e $HOME/.local/share/applications/$filename
	then
		rm $HOME/.local/share/applications/$filename
	fi
	# delete the game folder
	echo "Do you really want to delete all game files?"
	echo "0: cancel | 1: everything | 2: launcher files only"
	read confirm
	case $confirm in
		0)
			return
		;;
		1)
			echo "Deleting all files of the launcher and the game..."
			rm -r $game_folder
		;;
		2)
			echo "Deleting all files of the launcher..."
			rm -r $icon_location
		;;
	esac
	return
fi

# installation process
if ! [ $1 = "install" ]
then
	return
fi

downloadJar () {
	echo "Downloading launcher executable from "$launcher_last_url
	echo
	echo "========================="
	wget -P $icon_location $launcher_last_url
	echo "========================="
}

if ! test -d $icon_location
then
	echo "Creating folders for "$icon_location
	mkdir -p $icon_location
fi

if ! test -e $icon_location/$icon_filename
then
	echo "Downloading desktop icon from "$icon_url
	echo
	echo "========================="
	wget -P $icon_location $icon_url
	echo "========================="
else
	echo "Icon found in: "$icon_location
fi


# download the .jar file
if ! test -e $icon_location/$jar_filename
then
	downloadJar
else
	echo "Launcher executable found."
	echo "Do you still want to download the jar file? A newer version could be available.[y/n]"
	read update
	if [ "$update" = "y" ]
	then
		downloadJar
	fi
fi


#create the .desktop file
echo "Do you want to create a desktop entry for the launcher [y/n]"

read createShortcut

if [ "$createShortcut" = "y" ]
then
echo "Creating desktop shortcut file..."
touch $filename
echo "[Desktop Entry]" > $filename # overrides the file with the first thing, others are just appended
echo "# This .desktop file was auto-generated by the installation shell script." >> $filename
echo "Name=JPG Launcher" >> $filename
echo "Comment=A pixel-styled adventure game" >> $filename
echo "Terminal=false" >> $filename
echo "Exec=/bin/bash -c 'cd $icon_location && java -jar $jar_filename'" >> $filename
echo "Type=Application" >> $filename
echo "Categories=Games" >> $filename
echo "Icon="$icon_location/$icon_filename >> $filename
echo "Version=1.0" >> $filename
echo "File successfully created."
	if test -d $HOME/.local/share/applications
	then 
		mv $filename $HOME/.local/share/applications
	else
		echo "A desktop entry could not be made. Please put the file manually in the correct dir."
	fi

fi

echo "Installation is complete."
